# SwiftLint Configuration for Andernet Posture

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by editor
  - line_length # ARKit and medical code can have long lines
  - force_cast # Sometimes needed for AR types
  - force_try # OK in some contexts (e.g., loading bundled resources)
  - cyclomatic_complexity # Complex medical algorithms may exceed threshold

# Rule customization
identifier_name:
  min_length: 1 # Allow 'x', 'y', 'z' for coordinates
  max_length: 60
  excluded:
    - id
    - x
    - y
    - z
    - dx
    - dy
    - dz
    - i
    - j
    - k

type_name:
  min_length: 3
  max_length: 60

function_body_length:
  warning: 100
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

nesting:
  type_level: 2
  statement_level: 5

# Paths to include/exclude
included:
  - Andernet Posture

excluded:
  - Pods
  - Carthage
  - DerivedData
  - .build
  - Andernet PostureTests # Tests can have different rules
  - Andernet PostureUITests

# Reporter type
reporter: "xcode"
