# SwiftLint configuration for Andernet Posture

# Only lint the main app source
included:
  - Andernet Posture

excluded:
  - Andernet Posture/Assets.xcassets
  - DerivedData
  - build
  - .build
  - Pods

# Rules
disabled_rules:
  - trailing_whitespace        # noisy in Xcode-generated files
  - todo                       # allow TODO/FIXME during development

opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unowned_variable_capture
  - vertical_whitespace_closing_braces

# Tuning
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - dx
    - dy
    - dz
    - dt
    - lx
    - ly
    - lz
    - rx
    - ry
    - rz

nesting:
  type_level: 2
  function_level: 3

reporter: xcode
